# MengRain & Coldvvater-Config   (Stash)
# Date:2022.10.5
# æœ€åä¸€æ¬¡æ›´æ–°äºï¼š2022.10.5
# Author: MengRain  ï¼ˆæˆ‘çš„TGé¢‘é“ï¼šhttps://t.me/mengyulianmian  å¯ä»é¢‘é“è¿›ç¾¤äº¤æµï¼‰
# ä¸‹è½½é…ç½®å,è¯·æ‰‹åŠ¨æ·»åŠ æœºåœºè®¢é˜…
# æ‰¾åˆ° {è¿œç¨‹è®¢é˜…} éƒ¨åˆ†ï¼Œå°†MyProxy éƒ¨åˆ†çš„ urlæ›¿æ¢ä¸ºè‡ªå·±çš„æœºåœºè®¢é˜…é“¾æ¥  

subscribe-url: ä½ çš„è®¢é˜…é“¾æ¥
# æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

#æ··åˆç«¯å£
mixed-port: 7890
#å…è®¸å±€åŸŸç½‘
allow-lan: true
#ç»‘å®šåœ°å€
bind-address: '*'
#æ¨¡å¼:ruleï¼ˆè§„åˆ™ï¼‰ / globalï¼ˆå…¨å±€ä»£ç†ï¼‰/ directï¼ˆå…¨å±€ç›´è¿ï¼‰
mode: Rule
#æ—¥å¿—çº§åˆ«ï¼ˆæ—¥å¿—è¾“å‡ºçº§åˆ«ï¼šåˆ†çº§å¦‚åsilent / info / warning / error / debugçº§åˆ«è¶Šé«˜æ—¥å¿—è¾“å‡ºé‡è¶Šå¤§ï¼‰
log-level: silent
#å¤–éƒ¨æ§åˆ¶å™¨
external-controller: 127.0.0.1:9090

#DNSè®¾ç½®
dns:
  enable: true
  listen: 0.0.0.0:1053
  #DNSæœåŠ¡å™¨
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 114.114.114.114
  #DoHæœåŠ¡å™¨
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.dns.sb/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  #åˆ—è¡¨ä¸­çš„åŸŸåå°†ä¸ä¼šè¢«è§£æä¸ºfake ipï¼Œè¿™äº›åŸŸåç›¸å…³çš„è§£æè¯·æ±‚å°†ä¼šè¿”å›å®ƒä»¬çœŸå®çš„IPåœ°å€
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'

#æœ¬åœ°ä»£ç†
proxies:

#è¿œç¨‹è®¢é˜…
proxy-providers:

  MyProxy: &MyProxy #å»ºç«‹é”šç‚¹
    url: https://sub.store/download/collection/MySub
    interval: 86400
    health-check:
      enable: true
      interval: 3600
      url: http://cp.cloudflare.com/generate_204
    
  #ç¾å›½èŠ‚ç‚¹
  MyProxy-US:
    <<: *MyProxy #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: "ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|American"
  
  #é¦™æ¸¯èŠ‚ç‚¹
  MyProxy-HK:
    <<: *MyProxy #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: "æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong"
  
  #æ—¥æœ¬èŠ‚ç‚¹
  MyProxy-JP:
    <<: *MyProxy #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: "æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan"
  
  #å°æ¹¾èŠ‚ç‚¹
  MyProxy-TW:
    <<: *MyProxy #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: "å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan"
  
  #æ–°åŠ å¡èŠ‚ç‚¹
  MyProxy-SG:
    <<: *MyProxy #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"

#ç­–ç•¥ç»„
proxy-groups:

  - name: Proxy
    type: select
    use:
      - MyProxy
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Proxy.png
  
  
  - name: US ç¾å›½
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - MyProxy-US
  
  - name: HK é¦™æ¸¯
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - MyProxy-HK
  
  - name: JP æ—¥æœ¬
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - MyProxy-JP
  
  - name: TW å°æ¹¾
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png
    use:
      - MyProxy-TW
  
  - name: SG æ–°åŠ å¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
    use:
      - MyProxy-SG
  
  - name: å…¨çƒ
    type: select
    proxies: &G
      - US ç¾å›½
      - HK é¦™æ¸¯
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
      - æ¼ç½‘ä¹‹é±¼
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/World_Map.png
  
  - name: å›½å¤–åª’ä½“
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png
  
  - name: Netflix
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
  
  - name: Disney+
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Disney.png
  
  - name: HBO
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/HBO.png
  
  - name: Youtube
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
  
  - name: Spotify
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png
  
  - name: TikTok
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png
  
  - name: Bilibili
    type: select
    proxies:
      - DIRECT
      - HK é¦™æ¸¯
      - TW å°æ¹¾
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Bilibili.png
  
  - name: Telegram
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
  
  - name: Twitter
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
  
  - name: Speedtest
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Speedtest.png
  
  - name: PayPal
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/PayPal.png
  
  - name: TestFlight
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TestFlight.png
  
  - name: Apple
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
  
  - name: Google
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google.png
  
  - name: Microsoft
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
  
  - name: Weibo
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Weibo.png
  
  - name: ä¸­å›½å¤§é™†
    type: select
    proxies:
      - DIRECT
      - US ç¾å›½
      - HK é¦™æ¸¯
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
      - æ¼ç½‘ä¹‹é±¼
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Mainland.png
  
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - Proxy
      - DIRECT
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Final01.png

#è¿œç¨‹è§„åˆ™é›†åˆ
rule-providers:

  ASN-rules: 
    behavior: classical
    interval: 86400
    name: ASN
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/ASN_China.yaml
    
  Netflix-rules:
    behavior: classical
    interval: 86400
    name: Netflix
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Netflix/Netflix.yaml

  Disney-rules:
    behavior: classical
    interval: 86400
    name: Disney
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Disney/Disney.yaml

  HBO-rules:
    behavior: classical
    interval: 86400
    name: HBO
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/HBO/HBO.yaml

  Youtube-rules:
    behavior: classical
    interval: 86400
    name: Youtube
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/YouTube/YouTube.yaml

  Spotify-rules:
    behavior: classical
    interval: 86400
    name: Spotify
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Spotify/Spotify.yaml

  TikTok-rules:
    behavior: classical
    interval: 86400
    name: TikTok
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/TikTok/TikTok.yaml

  Bilibili-rules:
    behavior: classical
    interval: 86400
    name: Bilibili
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/BiliBili/BiliBili.yaml

  Telegram-rules:
    behavior: classical
    interval: 86400
    name: Telegram
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Telegram/Telegram.yaml

  Clubhouse-rules:
    behavior: classical
    interval: 86400
    name: Clubhouse
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Clubhouse/Clubhouse.yaml

  ClubhouseIP-rules:
    behavior: classical
    interval: 86400
    name: ClubhouseIP
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ClubhouseIP/ClubhouseIP.yaml

  Twitter-rules:
    behavior: classical
    interval: 86400
    name: Twitter
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Twitter/Twitter.yaml

  Speedtest-rules:
    behavior: classical
    interval: 86400
    name: Speedtest
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Speedtest/Speedtest.yaml

  PayPal-rules:
    behavior: classical
    interval: 86400
    name: PayPal
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/PayPal/PayPal.yaml

  TestFlight-rules:
    behavior: classical
    interval: 86400
    name: TestFlight
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/TestFlight/TestFlight.yaml

  Apple-rules:
    behavior: classical
    interval: 86400
    name: Apple
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Apple/Apple.yaml

  Google-rules:
    behavior: classical
    interval: 86400
    name: Google
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Google/Google.yaml

  Microsoft-rules:
    behavior: classical
    interval: 86400
    name: Microsoft
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Microsoft/Microsoft.yaml

  Weibo-rules:
    behavior: classical
    interval: 86400
    name: Weibo
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Weibo/Weibo.yaml

  Mainland-rules:
    behavior: classical
    interval: 86400
    name: Mainland
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/China/China.yaml

  MainlandIP-rules:
    behavior: ipcidr
    interval: 86400
    name: MainlandIP
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml

  Global-rules:
    behavior: classical
    interval: 86400
    name: Outside
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Global/Global_Classical.yaml

#åˆ†æµè§„åˆ™å¼•ç”¨
rules:
  - RULE-SET,ASN-rules,DIRECT
  - RULE-SET,Netflix-rules,Netflix
  - RULE-SET,Disney-rules,Disney+
  - RULE-SET,HBO-rules,HBO
  - RULE-SET,Youtube-rules,Youtube
  - RULE-SET,Spotify-rules,Spotify
  - RULE-SET,TikTok-rules,TikTok
  - RULE-SET,Bilibili-rules,Bilibili
  - RULE-SET,Telegram-rules,Telegram
  - RULE-SET,Clubhouse-rules,å›½å¤–åª’ä½“
  - RULE-SET,ClubhouseIP-rules,å›½å¤–åª’ä½“
  - RULE-SET,Twitter-rules,Twitter
  - RULE-SET,Speedtest-rules,Speedtest
  - RULE-SET,PayPal-rules,PayPal
  - RULE-SET,TestFlight-rules,TestFlight
  - RULE-SET,Apple-rules,Apple
  - RULE-SET,Google-rules,Google
  - RULE-SET,Microsoft-rules,Microsoft
  - RULE-SET,Weibo-rules,Weibo
  - RULE-SET,Mainland-rules,ä¸­å›½å¤§é™†
  - RULE-SET,MainlandIP-rules,ä¸­å›½å¤§é™†
  - RULE-SET,Global-rules,Proxy
  #- GEOIP,CN,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼
